<script>


    $('.btn-update').click(function(){
            var id = $(this).attr('data-id')
            var agent = $(this).attr('data-agent')
            var no = $(this).attr('data-no')
            var type = $(this).attr('data-type')
            var grade = $(this).attr('data-grade')
            var status = $(this).attr('data-status')
            var date = $(this).attr('data-date')
            var name = $(this).attr('data-name')
            var tel = $(this).attr('data-tel')
            var car = $(this).attr('data-car')
            var prise = $(this).attr('data-prise')
            var date_out = $(this).attr('data-date-out')
            var name_out = $(this).attr('data-name-out')
            var tel_out = $(this).attr('data-tel-out')
            var car_out = $(this).attr('data-car-out')
            var prise_out = $(this).attr('data-prise-out')

            $('#hidden_id_update').val(id)
            $('#update_agent').val(agent)
            $('#update_no').val(no)
            $('#update_type').val(type)
            $('#update_grade').val(grade)
            $('#update_status').val(status)
            $('#update_date').val(date)
            $('#update_name').val(name)
            $('#update_tel').val(tel)
            $('#update_car').val(car)
            $('#update_prise').val(prise)
            $('#update_date_out').val(date_out)
            $('#update_name_out').val(name_out)
            $('#update_tel_out').val(tel_out)
            $('#update_car_out').val(car_out)
            $('#update_prise_out').val(prise_out)


        })


        $('.btn-view').click(function(){
            var agent = $(this).attr('data-agent')
            var no = $(this).attr('data-no')
            var type = $(this).attr('data-type')
            var grade = $(this).attr('data-grade')
            var status = $(this).attr('data-status')
            var date = $(this).attr('data-date')
            var name = $(this).attr('data-name')
            var tel = $(this).attr('data-tel')
            var car = $(this).attr('data-car')
            var prise = $(this).attr('data-prise')
            var date_out = $(this).attr('data-date-out')
            var name_out = $(this).attr('data-name-out')
            var tel_out = $(this).attr('data-tel-out')
            var car_out = $(this).attr('data-car-out')
            var prise_out = $(this).attr('data-prise-out')

            $('#view_agent').val(agent)
            $('#view_no').val(no)
            $('#view_type').val(type)
            $('#view_grade').val(grade)
            $('#view_status').val(status)
            $('#view_date').val(date)
            $('#view_name').val(name)
            $('#view_tel').val(tel)
            $('#view_car').val(car)
            $('#view_prise').val(prise)
            $('#view_date_out').val(date_out)
            $('#view_name_out').val(name_out)
            $('#view_tel_out').val(tel_out)
            $('#view_car_out').val(car_out)
            $('#view_prise_out').val(prise_out)


        })

        $('.btn-delete').click(function(){
            var id = $(this).attr('data-id')
            var number = $(this).attr('data-no')
            $('#delete_id').val(id)
            $('#delete_number').val(number)
        })
    </script>
